config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "jobs#index"

  resources :jobs do
    resources :resumes
  end

  namespace :admin do
    resources :jobs do
      member do
        post :publish
        post :hide
      end

      resources :resumes
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, presence: true

  validates :lower_wage_bound, presence: true
  validates :lower_wage_bound, numericality: { greater_than: 0 }
  validates :upper_wage_bound, presence: true

  scope :published, -> { where(is_hidden: false) }
  scope :recent, -> { order("created_at DESC") }

  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end

  has_many :resumes

end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user
  belongs_to :job

  validates :content, presence: true

  mount_uploader :attachment, AttachmentUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def is_admin?
    is_admin
  end

  has_many :resumes

end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :create, :new, :edit, :update, :destroy]
  before_action :require_is_admin
  layout "admin"

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      flash[:notice] = "Job created"
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      flash[:notice] = "Update Successful"
      redirect_to admin_jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
      flash[:alert] = "Job Deleted"
      redirect_to admin_jobs_path
  end

  def publish
    @job = Job.find(params[:id])
    @job.publish!

    redirect_to admin_jobs_path
  end

  def hide
    @job = Job.find(params[:id])
    @job.hide!

    redirect_to admin_jobs_path
  end


  private

  def job_params
    params.require(:job).permit(:title, :description, :lower_wage_bound, :upper_wage_bound, :contact_email, :is_hidden)
  end

end

app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < ApplicationController
  before_action :require_is_admin
  layout "admin"

  def index
    @job = Job.find(params[:job_id])
    @resumes = @job.resumes.order("created_at DESC")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_is_admin
    if !current_user.is_admin?
      flash[:alert] = "you are not admin"
      redirect_to admin_jobs_path
    end
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]

  def index
    @jobs = case params[:order]
    when "wage_lower_bound"
      Job.published.order("lower_wage_bound DESC")
    when "wage_upper_bound"
      Job.published.order("upper_wage_bound DESC")
    else
      Job.published.recent
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      flash[:notice] = "Job created"
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      flash[:notice] = "Update Successful"
      redirect_to jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
      flash[:alert]= "Job Deleted"
      redirect_to jobs_path
  end


  private

  def job_params
    params.require(:job).permit(:title, :description, :lower_wage_bound, :upper_wage_bound, :contact_email, :is_hidden)
  end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!

  def new
    @job = Job.find(params[:job_id])
    @resume = Resume.new
  end

  def create
    @job = Job.find(params[:job_id])
    @resume = Resume.new(resume_params)
    @resume.job = @job
    @resume.user = current_user

    if @resume.save
      flash[:notice] = "Resume Submitted"
      redirect_to job_path(@job)
    else
      render :new
    end
  end


  private

  def resume_params
    params.require(:resume).permit(:content, :attachment)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "Welcome"
  end
  
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/admin/resumes_helper.rb
module Admin::ResumesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning" }.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end




end

app/helpers/jobs_helper.rb
module JobsHelper
  def render_job_status(job)
      if job.is_hidden
        content_tag(:span, "", class: "fa fa-lock fa")
      else
       content_tag(:span, "", class: "fa fa-globe fa")
      end
    end

end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/jobs/edit.html.erb
<h1> Edit Job </h1>

<%= simple_form_for [:admin, @job] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :lower_wage_bound %>
<%= f.input :upper_wage_bound %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

<%= f.submit "Submit", class: "btn btn-success" %>

<% end %>

app/views/admin/jobs/index.html.erb
<div class="pull-right">
    <%= link_to("Add a Job", new_admin_job_path, class: "btn btn-primary") %>
</div>
<br><br><br>


<table class="table table-bordered">
  <thead>
      <tr>
          <th> Title</th>
          <th> Resume</th>
          <th> Lower_wage_bound</th>
          <th> Upper_wage_bound</th>
          <th> Option</th>
      </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
          <td>
            <%= render_job_status(job) %>
             <%= link_to(job.title, job_path(job)) %>
           </td>
          <td> <%= link_to(job.resumes.count, admin_job_resumes_path(job)) %></td>
          <td> <%= job.lower_wage_bound %></td>
          <td> <%= job.upper_wage_bound %></td>
          <td>
            <%= link_to("Edit", edit_admin_job_path(job), class: "btn btn-success") %>
            <%= link_to("Delete", admin_job_path(job), method: :delete, :data => { :confirm => "Are you sure?" }, class: "btn btn-danger") %>

            <% if job.is_hidden %>
              <%= link_to("Publish", publish_admin_job_path(job),method: :post, class: "btn btn-success") %>
            <% else %>
              <%= link_to("Hide", hide_admin_job_path(job),method: :post, class: "btn btn-success") %>
            <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/admin/jobs/new.html.erb
<h1> Add a Job </h1>

<%= simple_form_for [:admin, @job] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :lower_wage_bound %>
<%= f.input :upper_wage_bound %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

<%= f.submit "Submit", class: "btn btn-success" %>

<% end %>

app/views/admin/resumes/_resume.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <span class="panel-title"> <%= resume.user.email %></span>
  </div>

  <div class="panel-body">

    <%= simple_format resume.content %>

  <hr>

  <% if resume.attachment.present? %>
    <%= link_to("Download Resume", resume.attachment_url) %>
  <% else %>
    No Attachment
  <% end %>

  </div>

</div>

app/views/admin/resumes/index.html.erb
<h1> <%= @job.title %> - Resume List </h1

<hr>

<%= render :partial => "resume", :collection => @resumes, :as => :resume %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">x</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">
    Copyright ©2017-2018 <br>
    Design by <a href="http://justincs.logdown.com/" target=_new>Justin Ng</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand & toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a href="/" class="navbar-brand"> Job-listing8 </a>
    </div>

    <!-- navbar collapse -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav pull-right">
        <% if !current_user %>
          <li> <%= link_to("Signup", new_user_registration_path) %></li>
          <li> <%= link_to("Login", new_user_session_path) %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi! <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.is_admin? %>
                <li> <%= link_to("Admin Panel", admin_jobs_path) %></li>
              <% end %>
              <li> <%= link_to("Logout", destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse end -->
  </div>
  <!-- /. container -->
</nav>

app/views/jobs/edit.html.erb
<h1> Edit Job</h1>

<%= simple_form_for @job do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :lower_wage_bound %>
<%= f.input :upper_wage_bound %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

<%= f.submit "Submit", class: "btn btn-success" %>

<% end %>

app/views/jobs/index.html.erb
<div class="dropdown pull-right">
  <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    List
  </button>

  <ul class="dropdown-menu">
    <li>
        <%= link_to("by_lower_bound", jobs_path(:order => "wage_lower_bound")) %>
    </li>
    <li>
        <%= link_to("by_upper_bound", jobs_path(:order => "wage_upper_bound")) %>
    </li><li>
        <%= link_to("list", jobs_path) %>
    </li>
  </ul>
</div>

<br><br><br>


<table class="table table-bordered">
  <thead>
      <tr>
          <th> Title</th>
          <th> Lower_wage_bound</th>
          <th> Upper_wage_bound</th>
          <th> Option</th>
      </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
          <td><%= link_to(job.title, job_path(job)) %> </td>
          <td> <%= job.lower_wage_bound %></td>
          <td> <%= job.upper_wage_bound %></td>
          <td>
            <%= link_to("Edit", edit_job_path(job), class: "btn btn-success") %>
            <%= link_to("Delete", job_path(job), method: :delete, :data => { :confirm => "Are you sure?" }, class: "btn btn-danger") %>
          </td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/jobs/new.html.erb
<h1> Add a Job</h1>

<%= simple_form_for @job do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :lower_wage_bound %>
<%= f.input :upper_wage_bound %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

<%= f.submit "Submit", class: "btn btn-success" %>

<% end %>

app/views/jobs/show.html.erb
<h1> <%= @job.title %></h1>

<%= simple_format @job.description %>

<div class="text-center" style="margin-top: 100px; font-size: 30px;">
  <%= link_to("Submit Resume", new_job_resume_path(@job)) %>

</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobListing8</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <div class="row">
        <div class="col-md-2">
          <ul class="nav nav-pills nav-stacked">
            <li class="active">
              <%= link_to("Jobs", admin_jobs_path) %>
            </li>
          </ul>
        </div>

          <div class="col-md-10">
            <%= yield %>
          </div>
      </div>
    </div>

        <%= render "common/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobListing8</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
       <%= yield %>
    </div>

        <%= render "common/footer" %>
  </body>
</html>

app/views/resumes/new.html.erb
<h1> Submit Resume for <%= @job.title %> </h1></hq>

<hr>

<%= simple_form_for [@job, @resume] do |f| %>

<%= f.input :content %>
<%= f.input :attachment %>

<%= f.submit "Submint", class: "btn btn-success" %>


<% end %>

app/views/welcome/index.html.erb
<h1> Welcome </h1>